export const EXPENSE_CATEGORIES = [
  "Other Business Expense",
  "Inventory & Resale Purchases",
  "Art Materials & Supplies",
  "Paper & Print Media",
  "Ink & Printing Supplies",
  "Frames & Display",
  "Packaging & Shipping Supplies",
  "Shipping & Postage",
  "Marketplace & Selling Fees",
  "Bank & Payment Processing Fees",
  "Advertising & Marketing",
  "Software & Subscriptions",
  "Phone / Internet",
  "Office Supplies",
  "Equipment & Tools",
  "Photography Equipment",
  "Repairs & Maintenance",
  "Professional Services",
  "Legal & Accounting",
  "Insurance",
  "Rent & Workspace",
  "Utilities",
  "Mileage & Vehicle",
  "Travel & Lodging",
  "Business Meals",
  "Education & Training",
  "Business Licenses & Fees",
  // Legacy categories kept for existing records.
  "Office & Business",
  "Inventory / Frames",
  "Printing Supplies",
  "Packaging",
  "Equipment",
  "Office Expense",
  "Advertising",
  "Shipping",
  "Other",
];

export const EXPENSE_CATEGORY_FILTERS = ["All", ...EXPENSE_CATEGORIES];
